export type TactivityLevel = 'sedentary' |'LightlyActive'| 'active' | 'veryActive'
export type Tactivities =
    'aerobics'|
    'americanFootball'|
    'badminton'|
    'baseball'|
    'basketball'|
    'bodyBuilding'|
    'bowling'|
    'boxing'|
    'canoeing'|
    'cheerLeading'|
    'climbing'|
    'cricket'|
    'cycling'|
    'dance'|
    'fencing'|
    'figureSkating'|
    'fishing'|
    'flagFootball'|
    'golf'|
    'gymnastics'|
  'handBall'|
  'hiking'|
  'horseRacing'|
  'iceHockey'|
  'iceSkating'|
    'judo'|
    'karate'|
    'kayaking'|
    'kickBall'|
    'lacrosse'|
    'martialArts'|
    'pickleBall'|
    'powerLifting'|
    'racquetBall'|
    'rodeo'|
    'rollerSkating'|
    'rowing'|
    'rugby'|
    'skateBoarding'|
    'skiing'|
    'soccer'|
    'softball'|
    'speedSkating'|
    'surfing'|
    'swimming'|
    'tableTennis'|
    'taekwondo'|
    'tennis'|
    'trackAndField'|
    'ultimateFrisbee'|
    'volleyball'|
    'waterPolo'|
    'weightLifting'|
    'wrestling';