export let itemSkeleton = ['name', 'price', 'reviewCount', 'reviewScore' ];
export let restaurantSkeleton = ['price', 'reviewCount', 'reviewScore', 'name', 'type', 'distance'];
export let nutrientSkeleton =
[
    'calories',
    'fat',
    'fatTrans',
    'fatSat',
    'monoUnsaturated',
    'polyUnsaturated',
    'carb',
    'protein',
    'fiber',
    'cholesterol',
    'vitaminA',
    'vitaminB6',
    'vitaminB12',
    'vitaminC',
    'vitaminD',
    'vitaminE',
    'vitaminK',
    'thiamin',
    'riboflavin',
    'niacin',
    'pantothenicAcid',
    'folate',
    'calcium',
    'iron',
    'magnesium',
    'phosphorus',
    'potassium',
    'sodium',
    'zinc', 
]